modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="naidru_more_items_mod"
version="1.0.0"
displayName="More Items Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.naidru_more_items_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



