modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="naidru_more_items_mod"
version="Beta 1.0.0_BuildB0001-1.15.2"
displayName="More Items Mod"
credits="N/A"
displayURL="https://github.com/EpicSkullYT/More-Items-Mod/"
logoFile="logo.png"
authors="Naidru"
description='''
Add more items, ore, and foods to your Minecraft world!
'''

[[dependencies.naidru_more_items_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



